---
# Source: elasticsearch/templates/manifests.yaml.template
apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-1-configmap
  labels:
    app.kubernetes.io/name: "elasticsearch-1"
    app.kubernetes.io/component: elasticsearch-server
data:
  elasticsearch.yml: |
    cluster.name: "${CLUSTER_NAME}"
    node.name: "${NODE_NAME}"

    path.data: /usr/share/elasticsearch/data
    path.repo: ["${BACKUP_REPO_PATH}"]

    network.host: 0.0.0.0

    discovery.zen.minimum_master_nodes: 2
    discovery.zen.ping.unicast.hosts: ${DISCOVERY_SERVICE}
  log4j2.properties: |
    status = error

    appender.console.type = Console
    appender.console.name = console
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] %marker%m%n

    rootLogger.level = info
    rootLogger.appenderRef.console.ref = console
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: elasticsearch-1-elasticsearch
  labels: &ElasticsearchDeploymentLabels
    app.kubernetes.io/name: "elasticsearch-1"
    app.kubernetes.io/component: elasticsearch-server
spec:
  selector:
    matchLabels: *ElasticsearchDeploymentLabels
  serviceName: elasticsearch-1-elasticsearch-svc
  replicas: 2
  updateStrategy:
      # The procedure for updating the Elasticsearch cluster is described at
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/rolling-upgrades.html
      type: OnDelete
  template:
    metadata:
      labels: *ElasticsearchDeploymentLabels
    spec:
      terminationGracePeriodSeconds: 180
      initContainers:
      # This init container sets the appropriate limits for mmap counts on the hosting node.
      # https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
      - name: set-max-map-count
        image: marketplace.gcr.io/google/elasticsearch/ubuntu16_04@sha256@sha256:281e570b1c254121ef9db4698554084a809d120aebfe14486c1014d0b6d4d3f5
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command:
        - /bin/bash
        - -c
        - 'if [[ "$(sysctl vm.max_map_count --values)" -lt 262144 ]]; then sysctl -w vm.max_map_count=262144; fi'
      containers:
      - name: elasticsearch
        image: marketplace.gcr.io/google/elasticsearch@sha256@sha256:d98e0b6b2567775552dbc22a8c56e258051699b88d1e090175bd88caecbc1d91
        imagePullPolicy: Always
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          value: "elasticsearch-1-cluster"
        - name: DISCOVERY_SERVICE
          value: "elasticsearch-1-elasticsearch-svc"
        - name: BACKUP_REPO_PATH
          value: ""
        ports:
        - name: http
          containerPort: 9200
        - name: tcp-transport
          containerPort: 9300
        volumeMounts:
        - name: configmap
          mountPath: /etc/elasticsearch/elasticsearch.yml
          subPath: elasticsearch.yml
        - name: configmap
          mountPath: /etc/elasticsearch/log4j2.properties
          subPath: log4j2.properties
        - name: elasticsearch-1-elasticsearch-pvc
          mountPath: /usr/share/elasticsearch/data
        readinessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command:
            - /usr/bin/pgrep
            - -x
            - "java"
          initialDelaySeconds: 5
        resources:
          requests:
            memory: "2Gi"
      volumes:
      - name: configmap
        configMap:
          name: "elasticsearch-1-configmap"
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-1-elasticsearch-pvc
      labels:
        app.kubernetes.io/name: "elasticsearch-1"
        app.kubernetes.io/component: elasticsearch-server
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: standard
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-1-elasticsearch-svc
  labels:
    app.kubernetes.io/name: "elasticsearch-1"
    app.kubernetes.io/component: elasticsearch-server
spec:
  ports:
  - name: http
    port: 9200
  - name: tcp-transport
    port: 9300
  selector:
    app.kubernetes.io/name: "elasticsearch-1"
    app.kubernetes.io/component: elasticsearch-server
  type: ClusterIP

---
# Source: elasticsearch/templates/application.yaml.template
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: "elasticsearch-1"
  namespace: "balls"
  annotations:
    kubernetes-engine.cloud.google.com/icon: >-
      data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIIAAACCCAYAAACKAxD9AAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAA3XAAAN1wFCKJt4AAAN/0lEQVR42u2dbWxU15nH/8+5d2Y8Mx6Px+92cHixCVAKLQoqAoXgwW3enUAjuwmBNoRNabdVumpFdtmoEqvuJgrbSivtqt2wZcOWgLKGGLpOU1iIbRKg26QBqW1aCBhsbEz8gj0ee95nzrMfTGk+ACW25859+39Bwpp7n3PmN/9znnPueS7BhOJtEKP33DlLCjmfCHMBzCXi2czwA1wIkB+A9yYfjwAIARglwigzXQDjHAucE2lx1l9/6SIR2Gx9RmZoxOixGXOl5BUA3wOIJSBeAIYnS7eLAHSGWZ4iohMkxfHC+p5OG4QcaKR9ViFx6j4WdD/AD4BRleOQegE6TOBDDMfRQLArZIOQJfWcnOH2xbmBidaB+EEwnDoNNQHQLwm8ZwSON2cHu+I2CFMd6xk02lFVz6CvM9BAQJ6h5ipAnIBWAu/w1/W9ree5hS5B4HaoI1TVSExbACwxyWzsFDFv9w/27acmZGwQbgVA80LnSFlo0wQAPBvmVCcxbfcP+XdR04dJG4QbAoCtAKphDXUT04v+gvJXaekHKcuD0H+4+q+dTrkVwAxYU51E2FpYd3mfJUHoOVBbF48r+zNpKvYXxZHnScHSIrRIxneKg5d7LQHCQPPC/Agl34zH1FWf/P98XxL5/rhJlrgmrRhA2wsH/S9qPX/QtNsvH6xZEY2rh9JJ4bvR3/PcafiLYyBiWNwe3pXgdVq6g9DqRl37a/9tfNxx/GYQAEA8pmJ4wAsphcVB4JWC6MNQe9VXTOMI55prSxXQ/yXi6pzb/YyiMAJlEaiqhNXFhB2BqPs5euh8wrAg9ByctSwWc72dSQnvp/2sokgEyqI2DBPf0klJ/ETxqr4eww0NXQdrvxUdz/vVZCAAgExGYLjfg3RasUFgrBCS3g+1Vd5tKEe40Fz7o0TC8d3pWFkXCqO4LALFdgYAGGHwo0XBvuO6d4Su/bV7EvHpgQAAZIYwPOiBlGRjAASI6O3h9qondA1C1/6aX8SijnXTHWQmPTFMMNskgOEk0N6Rtju+q8uh4cK+2oOJmOOxbPaB051GUUnUhuF6QsHPFgb7durGEbr2z92TbQgAIBlTMRZy2Qhc+xEz045Q2x1NugCh+43aF2NRdZ1WrY+MuRCPOWwMJvxcMGHXcEflypyC0NNS81w06tiqdftHr+YhnRI2CBNyE4tfTDW1nPQcoaulZnUi6jgiJeXkG1FVieKKiL0v8WddgZTLA/VXujUD4WzrXSU0Rr2ZtMjpgO32JuEvitsI/Pnb/G1sjJdXNfR96hn1pH7NSgQncg0BAMQiTsSj9nzhE6nlYo+PHtZkjnDhjdr/SCWVu/TS9vBInr1beZ0D+uFkn3T6VD3YdaDmwWTMsUlPjZeSEB6xU0oA/xU41vu3WZ8s8ltwnQvNu5pJT24TKdsqKonC6U5b1gkCdb3PT+XcxG07Qne0pkWvEADA6IjbikvQKRA9VxTs3TLVwzO3BcKl1tn3xWLOh/TcI5kMITrutBIE5yF4WaCu91+n42J/EQRmUHLcudcIB8EjYZf5dykZEqCdIkHLAqv6Tk/XZdW/OCQcqPlBKiWKjdBHUhIiYRd8hSZdWyC8J5ie8wd7fz39l76FBn8+zzcyTlczGTJMsk4ElFaOQSimmjAcZfA/ZOOBlNtyhPFk+pVMxmmoFRvmiY0pw7sCYQBM+6SUe4vr+05m/3Y3Ud/eu0rGmD6WGaEYsBNRVjUGIQzlCgkCTjPjCAt5JMBXfkVBaJYP39QRkq7EMifU40b9QaUSygWnOzWgx9gEkwQ4BIiQFOgRGfrIf7WnS4/H5W3ZsmXLli1btmzZsmXLli1btmzZuqGuLzGXP/X39SIRfthsDZQuTzz80DdOa9qphDhLOSxVGkyMjlzE5qUpw4Awo77xrOv8+3eZDnWhoP/7rZCunFXvTQP4AwFHJfGB2JNzTujxMMZ1EGYtujuthK+asirF8Nf/BYlZi/USzgWAXo46orvQtFA3lVcFAFSs/7s6s0IAAGr3h3oKZw7Ar3hT7t97Xut8RFcgKNHwEzCxnD1/1F1MDMwFUatnz8Uf461zLl2AQGNDK80MguPKeR1Hx990j6hvlew848u9I4QGZpoZBCXUD5HQ7xNLBF4ddbkO4ZU+T+5AaNzmVIb7vGYGAcxQhi7pPH/jFZ78+Otgzslj2KLCGaundBJmlzrQbYQwG7x7u57PCQiUiq2EBaQOXzaGeYG3uV4/V6P90JCIzrcCCCI8ZJRQ85SM8rLm/aMkIrOsAIIyNmykcNfm7z23UNuhIRYtt4QjjBsKBCGlslnTG4pkxGsJEMIjxgqY8ASaWbPVXoFEPM8KIFBizGghl7pTF+/WzhHi45YoQmTMFJmWazdHSCctUe2aMhIkjXWQiCA1y+gEZMY6Zc+N5gpM1do5QsY6dYcoZSwQSKBAO0ewa9/r2BG0q1MjWLVOwUp2OA3GAUa1cwSTlRa5pVSn0RyhS0NHcFoDBBJgo9X8EHxGs1vJvHxLvJTZiEOggDymHXMujyXKm0u3z2gh944/WfsH7UBwuiOWAMFbaLSEYY+W5x+EdOd/bAkQ8gNGCjfNUHdoOgzJPG+XJUDwGQkEfi3+1MwL2s5HnHlnbUfQ1drBGITjBc0npuQo6LACCOmiO4yR5TI9H33yzj7NQejzVrdLp/kfSUiXzjCCG+yJrp/977lJVXdsTslApekzh0yx7kH435gj9kyubi4AIOMv7TYzBNKVh4xP1wXmW6MOx5pcno4WAMC+kndNPSyUzZko267D0YAZ/xyt6v4ymqpjuQxEBYBkQfGePGCzWUFI3blAh7NC/J4k/010fc3beghHAMDgrh+8KwtKTPuESqpqnp4mhGcI+FpUnf35iE4guO4IE5019yNXeOgzpgShOqeOkAL4d0w4ChItsSdn/1qPfXQdhHTJzKfTy8qDpswYispPk8aPYknBUUncnyjv7UYwaM33ENqyZcuWLVu2bNmyZcuWLVu2bNkyr266JTfrjZ1PjyfS3zdy44o87o/v8BforpwaM4XBCAEIARgSoI8AOttW33BZdyAsbG7O74z2j8RTadWoIHzhzhnwOAx1sGUEhOPE1JFR+Mg7q9b8LucgAMCMfTt39IbCzxrUDbC4ssLYfs04TYRdzmTytcMPNA3nDIS69nb1vUsfhqPJlNtoffi5ygoEPG6YQQwkBfDfAP1T++rHsvLUubjVHzuCwXQgz/2S0TrO63KaBoJrv1YnAxsk+Ld17QdfWn6y2a2pI/xJgd0/uTISjxvGZxdVVKDYax4QbqBOEL7REVxzVBNHuD7e5rsfURVj1FEodOeZHQIAqAHjSLDt4M8aWls9moHQufbpD8rz85uN0EOzA0WWyf0Z2BD2ZtpXvvNGpSYgAEDFnMUbClyusN4zBb/bBSuJgC+ItHq8rv3ntZqA8MHSpSm/2/2IKoQuhwhBhNqSYlhRBJ7DzCeCbf+zMOsgAEBP48Z3ywt8L+jxhMDMQKHRFo+m2xnKGNx+77HWuVkHAQAuNz7zUlm+T1dP4nqcTlQH/LDFpZTJPK0JCADgjit1PpdrVC/Nry0uggDZHICOjxf0b9MMhK6NG+Olhe4vuRxqzosbVxUUoMjjthkArghOr/9g6eaUZiAAwIVHN75fXeh/2KEoMlct9zodqC0JWJ4ABgakoqxqq3980oeZxVQCOL/mq4cr/N5NiqJ9JiFAmF9WCkHC6hyMK8wN76xqOKdJ+njTTOLxTbvKvB7N9yNmFhXC53JZHYIEgde01a99b+o/rOkYnL7y7AtVhb7/JI2Onpd4vZgZKLQ6BAzib7WvXjstB2mnzVf7Gv9q0wx/wQ+FyC4MPpcLnykrtToEKQLWdwTX7py+oXYa1dP4zJZyj+8FkSVnUIXAgvJSZBs2nWuMwA+2r16zd1oTz2xEWrn3p5sH45GfpDNy2q4vSGBxVTkK8/IszAANgvBQR/Cx30z7lbMVcm3r7rorI6OHI4nUlGvjEwGfrShHscdjZSfoFMz3t9Wv7cxOFpYlnW/Y0DGvqODzRR53aKrXml9aanUIfqNmlNXZgiCrIADAqUe++sfFSVdlaX7+pK2stqQI5b58K+cGL4P8y49+qeFSVgcdrdoz7+DP/rE7NLo1nkrfNnzzSktRWZBv0e8fYTB/+1j92t2azD60bNySQ69/rmc4fGQoEim99ZyAsKC0BGXWdYITUhEb3ln16EXNpqHao85U0bzzp0ORyMYbZRWCCPOtC8EQAd9rDz62W8t3NeQGhGta8Obrnw2Nh1v6x6Nz5bU6V05FxaLKMksuHTO4hUh+pyP4eG9OEtNcd8C8lt1P9UfHf5yWsmBRRTlcqmoxAPAepPj2sS8++n5OVyj00BmNzc3O3kLxTZeqfg9AtUUY6Cbwi+GCgVcn+wyB6UD4JBADxY5NRLQFwGyTAtBJ4O0lQ6ld+5qadPOOYl0u2te1t6ssQ40E2gLCEpPMAU4R0fbSweT+fU1Nunttve53b+491rJApMXXmLCRgDKDjf8DxHgVQtnVEWw4o+dYDbONt/xkszsv7mhgYB2DHiRAr+/3TYDxSwjsAfxvdgSDhnivpiH3c+vaDxQS4z4J3A/QAwRU5TikXoAOg/gQwEc7gmtDRutTU2zs33usda6QcgUk3wPCEgYWEJCtXaoIJkrtn2KiE0LK49ncDLJBmIq2bRNfvGfRrBSJeQQxE4JnglENoARA+bV/vQx4/zTEMJCkiS85AmAIQD+AIQJfYqJugLrVTPqjo/Vfvqj1qp8W+n9/nuwKlmDfQQAAAABJRU5ErkJggg==
    marketplace.cloud.google.com/deploy-info: '{"partner_id": "click-to-deploy-containers", "product_id": "elasticsearch", "partner_name": "Google Click to Deploy"}'
  labels:
    app.kubernetes.io/name: "elasticsearch-1"
spec:
  descriptor:
    type: Elasticsearch
    version: '6.3'
    description: |-
      Elasticsearch is an open-source search engine that provides a distributed, multitenant-capable
      full-text search engine with an HTTP web interface and schema-free JSON documents.

      # Support
      Google does not offer support for this solution. However, community support is available on
      [Stack Overflow](https://stackoverflow.com/questions/tagged/elasticsearch/).
      Additional community support is available on [elastic.co forums](https://discuss.elastic.co/).
    maintainers:
    - name: Google Click to Deploy
      url: https://cloud.google.com/solutions/#click-to-deploy
    links:
    - description: 'User Guide: Google Click to Deploy Elasticsearch'
      url: https://github.com/GoogleCloudPlatform/click-to-deploy/blob/master/k8s/elasticsearch/README.md
    - description: 'Elasticsearch: Getting Started'
      url: https://www.elastic.co/webinars/getting-started-elasticsearch
    notes: |-
      # Expose Elasticsearch service

      By default, the service does not have an external IP. Run the
      following command to expose an external IP:

      ```
      kubectl patch service/"elasticsearch-1-elasticsearch-svc" \
        --namespace "balls" \
        --patch '{"spec": {"type": "LoadBalancer"}}'
      ```

        # Access Elasticsearch

        Get the external IP of the Elasticsearch service:

      ```
      SERVICE_IP=$(kubectl get service/elasticsearch-1-elasticsearch-svc \
        --namespace balls \
        --output jsonpath='{.status.loadBalancer.ingress[0].ip}')

      echo "http://${SERVICE_IP}:9200"
      ```

      Note that it might take some time for the external IP to be provisioned.

      # Scale the cluster

      To scale the cluster, use either a GKE UI (use the Scale option in the
      StatefulSet details screen) or the following command:

      ```
      kubectl scale statefulsets "elasticsearch-1-elasticsearch" \
        --namespace "balls" --replicas=<new-replicas>
      ```

      By default, there are 2 replicas to satisfy the minimum master quorum.
      To increase resilience, it is recommended to scale the number of replicas
      to at least 3.

      For more information about the StatefulSets scaling, check the
      [Kubernetes documentation](https://kubernetes.io/docs/tasks/run-application/scale-stateful-set/#kubectl-scale).
  selector:
    matchLabels:
      app.kubernetes.io/name: "elasticsearch-1"
  componentKinds:
  - group: v1
    kind: ConfigMap
  - group: v1
    kind: PersistentVolumeClaim
  - group: v1
    kind: Service
  - group: apps/v1beta2
    kind: StatefulSet

---
# Source: elasticsearch/templates/elasticsearch-1_manifest.yaml

